# "Constants" file

GREEN = (0, 128, 0)  # this is green
BACKGROUND = (0, 0, 0)  # this is black
PAUSED_BACKGROUND = (50, 50, 50)

BUTTON_WIDTH = 200
BUTTON_HEIGHT = 50
BUTTON_OFFSET = 10

ASTEROID_WINDOW_WIDTH = 800
ASTEROID_WINDOW_HEIGHT = 800

ASTEROID_WINDOW_OFFSET = BUTTON_WIDTH + BUTTON_OFFSET * 2

SCREEN_WIDTH = ASTEROID_WINDOW_HEIGHT + ASTEROID_WINDOW_OFFSET
SCREEN_HEIGHT = 800

FPS = 60
